# Changes here will be overwritten by Copier
_commit: ddac80a
_src_path: .
add_extension: js
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A JavaScript-Python project template
project_name: js template
python_version_primary: '3.11'
team: Python Project Template Authors
